version: '3'

services:
  app:
    container_name: shomrkm-app
    build: .
    tty: true
    working_dir: /usr/src/app
    ports:
      - 8080:3000
    volumes:
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
      - dist:/usr/src/app/dist

volumes:
  node_modules: {}
  dist: {}
